//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnoClinic.Services.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InnoClinic.Services.Application.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose the service category.
        /// </summary>
        internal static string ServiceCategory_Required {
            get {
                return ResourceManager.GetString("ServiceCategory_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid service category.
        /// </summary>
        internal static string ServiceCategoryInvalid {
            get {
                return ResourceManager.GetString("ServiceCategoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceId is required..
        /// </summary>
        internal static string ServiceId_Required {
            get {
                return ResourceManager.GetString("ServiceId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the name.
        /// </summary>
        internal static string ServiceName_Required {
            get {
                return ResourceManager.GetString("ServiceName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name is required.
        /// </summary>
        internal static string ServiceNameRequired {
            get {
                return ResourceManager.GetString("ServiceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve entered an invalid price.
        /// </summary>
        internal static string ServicePrice_Invalid {
            get {
                return ResourceManager.GetString("ServicePrice_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than 0.
        /// </summary>
        internal static string ServicePriceInvalid {
            get {
                return ResourceManager.GetString("ServicePriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one service is required.
        /// </summary>
        internal static string ServicesRequired {
            get {
                return ResourceManager.GetString("ServicesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status must be true (Active) or false (Inactive).
        /// </summary>
        internal static string ServiceStatus_Invalid {
            get {
                return ResourceManager.GetString("ServiceStatus_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization with this Id does not exist..
        /// </summary>
        internal static string SpecializationIdInvalid {
            get {
                return ResourceManager.GetString("SpecializationIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the name.
        /// </summary>
        internal static string SpecializationNameRequired {
            get {
                return ResourceManager.GetString("SpecializationNameRequired", resourceCulture);
            }
        }
    }
}
