version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: dev-auth-mssql
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Your_strong_password123
      - ACCEPT_EULA=Y
    volumes:
      - mssqldata:/var/opt/mssql
    restart: unless-stopped

  backend:
    build:
      context: ./Server/API
      dockerfile: Dockerfile
    container_name: dev-auth-backend
    ports:
      - "5179:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    restart: always

volumes:
  mssqldata:
